// Command notification-service runs the notification microservice.
//
// It is a pure gRPC server: it implements NotificationService and calls no
// other service, making it a leaf in the call graph. There is no HTTP port —
// only other services talk to it, never a browser or curl.
//
// This file is wiring only (ports, server setup, startup). The behaviour of the
// RPCs lives in server.go, which knows nothing about sockets or Protobuf.
package main

import (
	"log"
	"net"

	pb "github.com/demo/grpc-demo/proto/notifpb"
	"google.golang.org/grpc"
)

func main() {
	// Open a plain TCP socket. Nothing gRPC-specific has happened yet — gRPC
	// does not own the socket, it is handed one that is already listening.
	lis, err := net.Listen("tcp", ":9090")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// The gRPC engine: it speaks HTTP/2, routes each incoming request to the
	// right method, and serializes in both directions. At this point it knows
	// about zero services.
	s := grpc.NewServer()

	// Generated by protoc. Tells the engine "requests for NotificationService
	// go to this object". Without this line the server still starts and listens
	// happily, but answers every request with Unimplemented — a confusing
	// failure, because nothing looks broken.
	pb.RegisterNotificationServiceServer(s, &notifServer{})

	log.Println("notification-service gRPC listening on :9090")

	// Accept connections forever. Serve blocks until shutdown or a fatal error,
	// so nothing may follow it in main.
	log.Fatal(s.Serve(lis))
}
